### ISSUE TITLE
Is there a solution for VcXsrv mentioned inarticle

### ISSUE THREAD

**Issue by One2INF** [ishkapoor2000/Install_ROS_Noetic_On_WSL#1]
> Note: These settings might look different depending on when in the future you have downloaded VcXsrv. Warning: Everytime you re-start your PC, you need to check and un-check the options again (mentioned above). The solution for this is coming soon!

Hi [ishkapoor2000](https://github.com/ishkapoor2000). Your article really help me a lot. I'm wondering is there a solution now? Thanks!

**Comment by ishkapoor2000** [comment]
Hey @One2INF . Thanks for reaching out. There's one solution I found that gave me a relief. You may run XLaunch shortcut on your desktop and save that as a configuration file `config.xlaunch`. That'll save you time. But you still need to start the configuration file. It acts as a server for your rendering in ROS. You can search on the internet on how to run configuration files via `.bash`. That'll make it more easy for you.

**Comment by One2INF** [comment]
> You can search on the internet on how to run configuration files via `.bash`. That'll make it more easy for you.

Thank you! I will try that.
